[project]
readme = "README.md"
python = "^3.6"

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
#write_to = "ldndc2nc/_version.py"
local_scheme = "no-local-version"
